# Open a luks-encrypted device
#
# This effectively extends the luks_device module to manage creating and
# removing key file.
#
# Create device:
#
#   cryptsetup luksFormat /dev/device
#
# Configure role:
#
#   vars:
#     luks_key: "{{ vault_luks_key }}"  # secret key string
#     luks_device: sda2                 # path relative to /dev
#     luks_name: lvx0    # Name of open device, presents as /dev/mapper/lvx0

- name: Check for luks device
  stat:
    path: "/dev/mapper/{{ luks_name }}"
  register: mapped

- name: Open luks device
  include_tasks: luks_open_decrypt.yml
  when: not mapped.stat.exists
