# Reboot for kernel or other systemic upgrades.

- include_vars: "{{ ansible_distribution }}.yml"

- name: Check if reboot is required
  command: '{{ reboot_test }}'
  args:
    warn: false
  register: reboot_required
  failed_when: false
  changed_when: reboot_required.rc == 1

- name: Reboot if required
  reboot:
  when: reboot_required.changed
