- name: Scan target for ssh keys
  command: 'ssh-keyscan {{ target }}'
  register: key_scan

- name: Add keys to current known_hosts
  known_hosts:
    name: "{{ target }}"
    key: "{{ key_scan.stdout }}"
