- name: scan target for ssh keys
  ansible.builtin.shell: 'ssh-keyscan -p {{ scan_port | default(22) }} -t {{ key_type | default("rsa,ecdsa,ed25519") }} {{ target }} | sort'
  register: key_scan
  changed_when: no
  check_mode: no

- name: add keys to known_hosts
  ansible.builtin.blockinfile:
    path: '{{ known_hosts }}'
    block: '{{ key_scan.stdout }}'
    marker: '# {mark} {{ target }} KEY BLOCK'
    backup: yes
